givenName = input("Given name:")
familyName = input("Family name:")
streetAddress = input("Street address:")
cityAndPostalCode = input("City and postal code:")
print(f"{givenName} {familyName}")
print(streetAddress)
print(cityAndPostalCode)